<a href="https://colab.research.google.com/github/pogoreli/NNFS/blob/main/NNFS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install nnfs

In [ ]:
import numpy as np
from nnfs.datasets import spiral_data

In [ ]:
class Activation_ReLU:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)

In [ ]:
class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))

  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

In [ ]:
class Activation_Softmax:
  def forward(self, inputs):
    exp_values = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
    probabilities = exp_values / np.sum(exp_values, axis = 1, keepdims = True)
    self.output = probabilities

In [ ]:
class Loss:
  def calculate(self, output, y):
    sample_losses = self.forward(output, y)
    data_loss = np.mean(sample_losses)
    return data_loss

In [ ]:
class Loss_CategoricalCrossentropy(Loss):
  def forward(self, y_pred, y_true):
    samples = len(y_pred)
    y_pred_clipped = np.clip(y_pred, (1e-7), 1 - (1e-7))

    if len(y_true.shape) == 1:
      correct_confidences = y_pred_clipped[
          range(samples),
          y_true
      ]

    elif len(y_true.shape) == 2:
      correct_confidences = np.sum(
          y_pred_clipped * y_true,
          axis=1
      )

    negative_log_likelihoods = -np.log(correct_confidences)
    return negative_log_likelihoods

In [ ]:
inputs =  [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]

In [ ]:
X, y = spiral_data(samples=100, classes=3)
dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()
dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()
loss_function = Loss_CategoricalCrossentropy()
dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output[:5])
loss = loss_function.calculate(activation2.output, y)
print("loss: ", loss)


predictions = np.argmax(activation2.output, axis=1)
if len(y.shape) == 2:
  y = np.argmax(y, axis = 1)
accuracy = np.mean(predictions == y)
print('acc: ', accuracy)


[[0.33333333 0.33333333 0.33333333]
 [0.33333293 0.33333374 0.33333332]
 [0.33333238 0.33333431 0.33333331]
 [0.33333187 0.33333483 0.3333333 ]
 [0.33333138 0.33333533 0.33333329]]
loss:  1.0986106002471583
acc:  0.35333333333333333
